// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxGhoPhox6sxipBI4cHpVvnVmdg-F3FbM',
    appId: '1:878065037425:web:49f993f7b9e24747b92bd0',
    messagingSenderId: '878065037425',
    projectId: 'trackrecords-377e3',
    authDomain: 'trackrecords-377e3.firebaseapp.com',
    storageBucket: 'trackrecords-377e3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQU-nAVGEgCkELQM3u8cVEZ0d1hv0hd24',
    appId: '1:878065037425:android:ba0bba71f123e1aab92bd0',
    messagingSenderId: '878065037425',
    projectId: 'trackrecords-377e3',
    storageBucket: 'trackrecords-377e3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5NBGqyujo9WBErCeiKLEjpfpHhJJ1GU0',
    appId: '1:878065037425:ios:2cb1147c203260bcb92bd0',
    messagingSenderId: '878065037425',
    projectId: 'trackrecords-377e3',
    storageBucket: 'trackrecords-377e3.firebasestorage.app',
    iosBundleId: 'com.example.trackRecordsAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5NBGqyujo9WBErCeiKLEjpfpHhJJ1GU0',
    appId: '1:878065037425:ios:2cb1147c203260bcb92bd0',
    messagingSenderId: '878065037425',
    projectId: 'trackrecords-377e3',
    storageBucket: 'trackrecords-377e3.firebasestorage.app',
    iosBundleId: 'com.example.trackRecordsAssignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxGhoPhox6sxipBI4cHpVvnVmdg-F3FbM',
    appId: '1:878065037425:web:6689aece387923ecb92bd0',
    messagingSenderId: '878065037425',
    projectId: 'trackrecords-377e3',
    authDomain: 'trackrecords-377e3.firebaseapp.com',
    storageBucket: 'trackrecords-377e3.firebasestorage.app',
  );
}
